<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Leave extends \OrangeHRM\Entity\Leave implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'date', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'lengthHours', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'lengthDays', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'status', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveRequest', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveType', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'startTime', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'endTime', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'durationType', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveLeaveEntitlements', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'date', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'lengthHours', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'lengthDays', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'status', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveRequest', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveType', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'startTime', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'endTime', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'durationType', '' . "\0" . 'OrangeHRM\\Entity\\Leave' . "\0" . 'leaveLeaveEntitlements', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Leave $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTime $date): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLengthHours(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLengthHours', []);

        return parent::getLengthHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setLengthHours(float $lengthHours): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLengthHours', [$lengthHours]);

        parent::setLengthHours($lengthHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getLengthDays(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLengthDays', []);

        return parent::getLengthDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setLengthDays(float $lengthDays): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLengthDays', [$lengthDays]);

        parent::setLengthDays($lengthDays);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeaveRequest(): \OrangeHRM\Entity\LeaveRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeaveRequest', []);

        return parent::getLeaveRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeaveRequest(\OrangeHRM\Entity\LeaveRequest $leaveRequest): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeaveRequest', [$leaveRequest]);

        parent::setLeaveRequest($leaveRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeaveType(): \OrangeHRM\Entity\LeaveType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeaveType', []);

        return parent::getLeaveType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeaveType(\OrangeHRM\Entity\LeaveType $leaveType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeaveType', [$leaveType]);

        parent::setLeaveType($leaveType);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee(): \OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\OrangeHRM\Entity\Employee $employee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartTime(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartTime', []);

        return parent::getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartTime(\DateTime $startTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartTime', [$startTime]);

        parent::setStartTime($startTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime(\DateTime $endTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationType(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationType', []);

        return parent::getDurationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationType(int $durationType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationType', [$durationType]);

        parent::setDurationType($durationType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
