<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeEducation extends \OrangeHRM\Entity\EmployeeEducation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'education', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'institute', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'major', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'year', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'score', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'startDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'endDate', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'education', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'institute', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'major', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'year', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'score', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'startDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeEducation' . "\0" . 'endDate', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmployeeEducation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation(): ?\OrangeHRM\Entity\Education
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', []);

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducation(\OrangeHRM\Entity\Education $education): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducation', [$education]);

        parent::setEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee(): ?\OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\OrangeHRM\Entity\Employee $employee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstitute(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstitute', []);

        return parent::getInstitute();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstitute(?string $institute): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstitute', [$institute]);

        parent::setInstitute($institute);
    }

    /**
     * {@inheritDoc}
     */
    public function getMajor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMajor', []);

        return parent::getMajor();
    }

    /**
     * {@inheritDoc}
     */
    public function setMajor(?string $major): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMajor', [$major]);

        parent::setMajor($major);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear(?int $year): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', []);

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore(?string $score): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', [$score]);

        parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(?\DateTime $startDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate(?\DateTime $endDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$endDate]);

        parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
