<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClaimRequest extends \OrangeHRM\Entity\ClaimRequest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'user', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'referenceId', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'claimEvent', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'description', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'currencyType', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'isDeleted', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'status', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'createdDate', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'submittedDate', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'employee', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'user', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'referenceId', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'claimEvent', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'description', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'currencyType', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'isDeleted', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'status', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'createdDate', '' . "\0" . 'OrangeHRM\\Entity\\ClaimRequest' . "\0" . 'submittedDate', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClaimRequest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee(): \OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\OrangeHRM\Entity\Employee $employee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \OrangeHRM\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\OrangeHRM\Entity\User $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferenceId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferenceId', []);

        return parent::getReferenceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferenceId(string $referenceId): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferenceId', [$referenceId]);

        parent::setReferenceId($referenceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimEvent(): \OrangeHRM\Entity\ClaimEvent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimEvent', []);

        return parent::getClaimEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimEvent(\OrangeHRM\Entity\ClaimEvent $claimEvent): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimEvent', [$claimEvent]);

        parent::setClaimEvent($claimEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyType(): \OrangeHRM\Entity\CurrencyType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyType', []);

        return parent::getCurrencyType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyType(\OrangeHRM\Entity\CurrencyType $currencyType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyType', [$currencyType]);

        parent::setCurrencyType($currencyType);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(bool $isDeleted): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(\DateTime $createdDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$createdDate]);

        parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmittedDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmittedDate', []);

        return parent::getSubmittedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmittedDate(?\DateTime $submittedDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmittedDate', [$submittedDate]);

        parent::setSubmittedDate($submittedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
