<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobTitle extends \OrangeHRM\Entity\JobTitle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobTitleName', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobDescription', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'isDeleted', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobSpecificationAttachment', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'employees'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobTitleName', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobDescription', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'isDeleted', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'jobSpecificationAttachment', '' . "\0" . 'OrangeHRM\\Entity\\JobTitle' . "\0" . 'employees'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JobTitle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitleName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitleName', []);

        return parent::getJobTitleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitleName(string $jobTitleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitleName', [$jobTitleName]);

        return parent::setJobTitleName($jobTitleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobDescription', []);

        return parent::getJobDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobDescription(?string $jobDescription): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobDescription', [$jobDescription]);

        parent::setJobDescription($jobDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote(?string $note): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(bool $isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobSpecificationAttachment(): ?\OrangeHRM\Entity\JobSpecificationAttachment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobSpecificationAttachment', []);

        return parent::getJobSpecificationAttachment();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobSpecificationAttachment(?\OrangeHRM\Entity\JobSpecificationAttachment $jobSpecificationAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobSpecificationAttachment', [$jobSpecificationAttachment]);

        return parent::setJobSpecificationAttachment($jobSpecificationAttachment);
    }

}
