<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmailConfiguration extends \OrangeHRM\Entity\EmailConfiguration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'mailType', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'sentAs', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpHost', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpPort', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpUsername', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpPassword', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpAuthType', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpSecurityType'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'mailType', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'sentAs', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpHost', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpPort', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpUsername', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpPassword', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpAuthType', '' . "\0" . 'OrangeHRM\\Entity\\EmailConfiguration' . "\0" . 'smtpSecurityType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmailConfiguration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailType', []);

        return parent::getMailType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailType(?string $mailType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailType', [$mailType]);

        parent::setMailType($mailType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentAs(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentAs', []);

        return parent::getSentAs();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentAs(string $sentAs): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentAs', [$sentAs]);

        parent::setSentAs($sentAs);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpHost(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpHost', []);

        return parent::getSmtpHost();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpHost(?string $smtpHost): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpHost', [$smtpHost]);

        parent::setSmtpHost($smtpHost);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpPort(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpPort', []);

        return parent::getSmtpPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpPort(?int $smtpPort): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpPort', [$smtpPort]);

        parent::setSmtpPort($smtpPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpUsername', []);

        return parent::getSmtpUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpUsername(?string $smtpUsername): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpUsername', [$smtpUsername]);

        parent::setSmtpUsername($smtpUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpPassword', []);

        return parent::getSmtpPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpPassword(?string $smtpPassword): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpPassword', [$smtpPassword]);

        parent::setSmtpPassword($smtpPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpAuthType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpAuthType', []);

        return parent::getSmtpAuthType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpAuthType(?string $smtpAuthType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpAuthType', [$smtpAuthType]);

        parent::setSmtpAuthType($smtpAuthType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpSecurityType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpSecurityType', []);

        return parent::getSmtpSecurityType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpSecurityType(?string $smtpSecurityType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpSecurityType', [$smtpSecurityType]);

        parent::setSmtpSecurityType($smtpSecurityType);
    }

}
