<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Interview extends \OrangeHRM\Entity\Interview implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'candidateVacancy', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'candidate', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewName', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewDate', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewTime', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewers', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'candidateVacancy', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'candidate', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewName', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewDate', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewTime', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\Interview' . "\0" . 'interviewers', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Interview $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidateVacancy(): ?\OrangeHRM\Entity\CandidateVacancy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidateVacancy', []);

        return parent::getCandidateVacancy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidateVacancy(?\OrangeHRM\Entity\CandidateVacancy $candidateVacancy): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidateVacancy', [$candidateVacancy]);

        parent::setCandidateVacancy($candidateVacancy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidate(): ?\OrangeHRM\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidate', []);

        return parent::getCandidate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidate(?\OrangeHRM\Entity\Candidate $candidate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidate', [$candidate]);

        parent::setCandidate($candidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewName', []);

        return parent::getInterviewName();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterviewName(string $interviewName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterviewName', [$interviewName]);

        parent::setInterviewName($interviewName);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewDate', []);

        return parent::getInterviewDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterviewDate(?\DateTime $interviewDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterviewDate', [$interviewDate]);

        parent::setInterviewDate($interviewDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewTime(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewTime', []);

        return parent::getInterviewTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterviewTime(?\DateTime $interviewTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterviewTime', [$interviewTime]);

        parent::setInterviewTime($interviewTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote(?string $note): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewers(): iterable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewers', []);

        return parent::getInterviewers();
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
