<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CandidateHistory extends \OrangeHRM\Entity\CandidateHistory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'candidate', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'vacancy', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'candidateVacancyName', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'interview', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'action', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'performedBy', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'performedDate', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'interviewers', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'candidate', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'vacancy', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'candidateVacancyName', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'interview', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'action', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'performedBy', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'performedDate', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'note', '' . "\0" . 'OrangeHRM\\Entity\\CandidateHistory' . "\0" . 'interviewers', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CandidateHistory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidate(): \OrangeHRM\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidate', []);

        return parent::getCandidate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidate(\OrangeHRM\Entity\Candidate $candidate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidate', [$candidate]);

        parent::setCandidate($candidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacancy(): ?\OrangeHRM\Entity\Vacancy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacancy', []);

        return parent::getVacancy();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacancy(?\OrangeHRM\Entity\Vacancy $vacancy): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacancy', [$vacancy]);

        parent::setVacancy($vacancy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidateVacancyName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidateVacancyName', []);

        return parent::getCandidateVacancyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidateVacancyName(?string $candidateVacancyName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidateVacancyName', [$candidateVacancyName]);

        parent::setCandidateVacancyName($candidateVacancyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterview(): ?\OrangeHRM\Entity\Interview
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterview', []);

        return parent::getInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterview(?\OrangeHRM\Entity\Interview $interview): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterview', [$interview]);

        parent::setInterview($interview);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction(int $action): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerformedBy(): ?\OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerformedBy', []);

        return parent::getPerformedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerformedBy(?\OrangeHRM\Entity\Employee $performedBy): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerformedBy', [$performedBy]);

        parent::setPerformedBy($performedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerformedDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerformedDate', []);

        return parent::getPerformedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerformedDate(\DateTime $performedDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerformedDate', [$performedDate]);

        parent::setPerformedDate($performedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote(?string $note): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewers(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewers', []);

        return parent::getInterviewers();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterviewers(?string $interviewers): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterviewers', [$interviewers]);

        parent::setInterviewers($interviewers);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
