<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmpWorkExperience extends \OrangeHRM\Entity\EmpWorkExperience implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'seqNo', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'employer', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'jobTitle', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'fromDate', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'toDate', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'comments', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'internal', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'employee', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'seqNo', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'employer', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'jobTitle', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'fromDate', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'toDate', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'comments', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'internal', '' . "\0" . 'OrangeHRM\\Entity\\EmpWorkExperience' . "\0" . 'employee', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmpWorkExperience $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSeqNo(): int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getSeqNo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeqNo', []);

        return parent::getSeqNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeqNo(int $seqNo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeqNo', [$seqNo]);

        parent::setSeqNo($seqNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployer', []);

        return parent::getEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployer(?string $employer): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployer', [$employer]);

        parent::setEmployer($employer);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitle', []);

        return parent::getJobTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitle(?string $jobTitle): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitle', [$jobTitle]);

        parent::setJobTitle($jobTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromDate', []);

        return parent::getFromDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromDate(?\DateTime $fromDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromDate', [$fromDate]);

        parent::setFromDate($fromDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getToDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToDate', []);

        return parent::getToDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setToDate(?\DateTime $toDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToDate', [$toDate]);

        parent::setToDate($toDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments(?string $comments): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternal', []);

        return parent::getInternal();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternal(?int $internal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternal', [$internal]);

        parent::setInternal($internal);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee(): ?\OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\OrangeHRM\Entity\Employee $employee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
