<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkflowStateMachine extends \OrangeHRM\Entity\WorkflowStateMachine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'workflow', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'state', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'role', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'action', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'resultingState', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'rolesToNotify', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'priority', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'workflow', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'state', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'role', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'action', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'resultingState', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'rolesToNotify', '' . "\0" . 'OrangeHRM\\Entity\\WorkflowStateMachine' . "\0" . 'priority', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WorkflowStateMachine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflow(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflow', []);

        return parent::getWorkflow();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflow(string $workflow): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflow', [$workflow]);

        parent::setWorkflow($workflow);
    }

    /**
     * {@inheritDoc}
     */
    public function getState(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState(string $state): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(string $role): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction(string $action): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultingState(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultingState', []);

        return parent::getResultingState();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultingState(string $resultingState): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultingState', [$resultingState]);

        parent::setResultingState($resultingState);
    }

    /**
     * {@inheritDoc}
     */
    public function getRolesToNotify(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolesToNotify', []);

        return parent::getRolesToNotify();
    }

    /**
     * {@inheritDoc}
     */
    public function setRolesToNotify(?string $rolesToNotify): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRolesToNotify', [$rolesToNotify]);

        parent::setRolesToNotify($rolesToNotify);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', []);

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority(int $priority): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', [$priority]);

        parent::setPriority($priority);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
