<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeLicense extends \OrangeHRM\Entity\EmployeeLicense implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'license', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseNo', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseIssuedDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseExpiryDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'employee', 'entityDecorator'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'license', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseNo', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseIssuedDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'licenseExpiryDate', '' . "\0" . 'OrangeHRM\\Entity\\EmployeeLicense' . "\0" . 'employee', 'entityDecorator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmployeeLicense $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLicense(): \OrangeHRM\Entity\License
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicense', []);

        return parent::getLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicense(\OrangeHRM\Entity\License $license): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicense', [$license]);

        parent::setLicense($license);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseNo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseNo', []);

        return parent::getLicenseNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseNo(?string $licenseNo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseNo', [$licenseNo]);

        parent::setLicenseNo($licenseNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseIssuedDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseIssuedDate', []);

        return parent::getLicenseIssuedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseIssuedDate(?\DateTime $licenseIssuedDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseIssuedDate', [$licenseIssuedDate]);

        parent::setLicenseIssuedDate($licenseIssuedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseExpiryDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseExpiryDate', []);

        return parent::getLicenseExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseExpiryDate(?\DateTime $licenseExpiryDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseExpiryDate', [$licenseExpiryDate]);

        parent::setLicenseExpiryDate($licenseExpiryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee(): ?\OrangeHRM\Entity\Employee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\OrangeHRM\Entity\Employee $employee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecorator(): object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecorator', []);

        return parent::getDecorator();
    }

}
