<?php

namespace DoctrineProxies\__CG__\OrangeHRM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FilterField extends \OrangeHRM\Entity\FilterField implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'reportGroup', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'name', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'whereClausePart', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'filterFieldWidget', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'conditionNo', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'required', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'className', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'selectedFilterFields'];
        }

        return ['__isInitialized__', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'id', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'reportGroup', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'name', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'whereClausePart', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'filterFieldWidget', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'conditionNo', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'required', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'className', '' . "\0" . 'OrangeHRM\\Entity\\FilterField' . "\0" . 'selectedFilterFields'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FilterField $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportGroup(): \OrangeHRM\Entity\ReportGroup
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportGroup', []);

        return parent::getReportGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportGroup(\OrangeHRM\Entity\ReportGroup $reportGroup): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportGroup', [$reportGroup]);

        parent::setReportGroup($reportGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhereClausePart(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhereClausePart', []);

        return parent::getWhereClausePart();
    }

    /**
     * {@inheritDoc}
     */
    public function setWhereClausePart(string $whereClausePart): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWhereClausePart', [$whereClausePart]);

        parent::setWhereClausePart($whereClausePart);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterFieldWidget(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterFieldWidget', []);

        return parent::getFilterFieldWidget();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilterFieldWidget(?string $filterFieldWidget): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilterFieldWidget', [$filterFieldWidget]);

        parent::setFilterFieldWidget($filterFieldWidget);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionNo(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionNo', []);

        return parent::getConditionNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionNo(int $conditionNo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionNo', [$conditionNo]);

        parent::setConditionNo($conditionNo);
    }

    /**
     * {@inheritDoc}
     */
    public function isRequired(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRequired', []);

        return parent::isRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequired(bool $required): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequired', [$required]);

        parent::setRequired($required);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName', []);

        return parent::getClassName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassName(string $className): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassName', [$className]);

        parent::setClassName($className);
    }

}
